### ISSUE TITLE
An obstacle to start Gerbera after installation

### ISSUE THREAD

**Issue by Apfelgriebs** [v00d00/gerbera#104] opened 2017-06-30 17:49 UTC
On Ubuntu 17.04, when installing gerbera via the PPA, a gerbera.desktop file is also installed in `/usr/share/applications/`.

However, all this shortcut does is opening `/var/lib/gerbera/gerbera.html` in a browser. This file does not exist, so all I get is a 404 page.

Only when I run `gebera` in terminal, I get actual output, including the line

> INFO: The Web UI can be reached by following this link: http://192.168.178.21:49152/

When I open this URL in my browser, I finally get into using Gebera.

Expected behavior: The Gebera.desktop file should actually start the program out-of-the-box, making use easier for new users (like myself :) ). 

Gerbera version: 1:1.0.0.1
OS: Ubuntu 17.04
Desktop: Gnome 3.22

Content of gerbera.desktop:

```
[Desktop Entry]
Name=Gerbera
Comment=Gerbera UPnP MediaServer web user interface.
Exec=/usr/bin/x-www-browser /var/lib/gerbera/gerbera.html
Icon=gerbera.png
Terminal=false
Type=Application
Categories=AudioVideo;
```

**Comment by v00d00** [comment] 2017-06-30 17:53
@stephen-czetty can you sort this?

**Comment by v00d00** [comment] 2017-06-30 17:57
Actually we can probably rename this file, its still called `mediatomb` currently

**Comment by Apfelgriebs** [comment] 2017-06-30 17:59
All that exists in /var/lib/gerbera/ is a database file named gerbera.db. There is no html file present.

**Comment by v00d00** [comment] 2017-06-30 18:07
The html file gets created dynamically when the service starts, so if gerbera is running it should be there!

**Comment by Apfelgriebs** [comment] 2017-06-30 18:08
I've run and stopped gerbera some times now, there is still no html file.

**Comment by v00d00** [comment] 2017-06-30 18:09
Perhaps the location has been changed in config.xml? is there a bookmark tag?

**Comment by Apfelgriebs** [comment] 2017-06-30 18:14
I don't know what I have to look for exactly. Here is the content of `~/.config/gerbera/config.xml`:

https://pastebin.com/xbPw7wYu

**Comment by v00d00** [comment] 2017-06-30 18:36
Doesnt look like its overridden in your config.

The file gets created in different places depending on how you run it, as it looks for a config file in different places.

If you run it from a shell (as your user) it will use the config in your home directory (and use the location set in the `<home>` tag.

If you run it as a system daemon (eg `systemctl start gerbera`) then it gets created in `/var/lib/gerbera/` ie the `gerbera` system user home directory.

**Comment by Apfelgriebs** [comment] 2017-06-30 19:35
Seems like `mediatomb.html` was actually created in `~/.config/gerbera/`, alongside with `config.xml` and `mediatomb.db`.

Regarding systemd, gerbera has an entry but failed for some reason. Should I open a new issue for that or continue here? :)

Output of `systemctl status gerbera.service` is here: https://pastebin.com/Zr2nPraG and output of journalctl here: https://pastebin.com/jA7y3aBP

My wifi interface is `wlx00c0ca598ac3`, eth0 doesn't exist on this computer.

**Comment by v00d00** [comment] 2017-07-02 11:50
It looks you need to $MT_INTERFACE somewhere? This seems to be in the packaging somewhere though. Hopefully @stephen-czetty can comment.

**Comment by v00d00** [comment] 2017-07-07 18:31
I'm going to close this. Feel free to open the systemd issue if you think it's needed 🙂

**Closed** 2017-07-07 18:31 UTC
Labels: bug

**Comment by HawkEyeVe** [comment] 2018-02-19 23:10
Hi plz  help me how can i put the sutitles  on gerbera i cant fine nothing related on de config.xml

**Comment by elmodaddyb** [comment] 2018-02-20 08:55
Hello @HawkEyeVe - I haven’t had much experience with video files that contain a subtitle track but here are some thoughts. 

1. Does your video already contain a muxed subtitle track?

> If yes then it might be possible to render the subtitles given...

A. The upnp media render (client playing video) supports the ability to pick up and process the separate SRT subtitle track.
B. Gerbera sends the proper headers to make the media renderer **aware** of the subtitles in the file. 
> Gerbera currently does not support custom headers at this time, so you'd have to code some c++ in the libupnp library.

2. If the video does not contain the subtitle track, and you have a separate SRT track

> you might be able to leverage a specific transcoding profile to dynamically burn in the SRT subtitles??

This is just a brainstorm. Let me know what type of setup you have. Maybe we can figure out a solution.

**Comment by HawkEyeVe** [comment] 2018-02-20 16:10
i download the SRT file change the name to the exact name of the video and is not reproducin de subtitile in other DLNA server works but in gerbera dosnt work for example in plex an in UMS the SRT works fine

**Comment by elmodaddyb** [comment] 2018-02-20 23:58
@HawkEyeVe - Looking through the Gerbera code, it appears that the system renders out the **CaptionInfo** with the similarly named SRT file resource, when the the extended protocol info is turned ON and samsung hack is enabled.

Not sure if this is entirely applicable to your media-render but you could try this configuration setting:

```xml
<config>
   <server>
      ...
      <protocolInfo extend="yes" samsung-hack="yes"/>
      ...
   </server>
</config>
```

This working would depend on your media renderer looking @ the same UPNP header `CaptionInfo.sec: <http://video-name.srt>` as Samsung's devices(not sure if this applies).

Based on your results here, we may want to open a new issue to accommodate caption info content for compliant renders, not only samsung devices.
