### ISSUE TITLE
Adding image item with web interface: Crash

### ISSUE THREAD

**Issue by cweiske** [v00d00/gerbera#83] opened 2017-05-05 21:18 UTC
I tried to use add a cover.jpg image item with the web interface.

Data:
- Select folder
- "add Item"
- type: Item
- title: `cover.jpg`
- location: `/var/spool/music/Hörspiele/cover.jpg`
- class: `object.item.imageItem`
- description: (none)
- mime type: `image/jpeg`

When clicking "add item", gerbera crashes:

```
2017-05-05 23:17:33   ERROR: Exception caught: Script: failed to execute script
Exception raised in [src/scripting/script.cc:304] _execute(): Script: failed to execute script
2017-05-05 23:17:33   ERROR: Exception caught: Script: failed to execute script
Exception raised in [src/scripting/script.cc:304] _execute(): Script: failed to execute script
gerbera: /usr/local/src/gerbera/src/storage/sql_storage.cc:223: zmm::Ref<CdsObject> SQLStorage::checkRefID(zmm::Ref<CdsObject>): Zusicherung »0« nicht erfüllt.
systemd[1]: gerbera.service: main process exited, code=killed, status=6/ABRT
systemd[1]: Unit gerbera.service entered failed state.
```

"Zusicherung »0« nicht erfüllt" is german and emeans "assertion 0 not fulfilled".

**Comment by v00d00** [comment] 2017-05-06 14:56
So if you look at the assert[1] there is a comment that it should never happen...

We always enable the asserts now though, so it is crashing. Perhaps it is no longer a valid assertion?

1. https://github.com/v00d00/gerbera/blob/master/src/storage/sql_storage.cc#L223

**Comment by v00d00** [comment] 2017-05-06 14:58
This is a dupe of #73

**Closed by v00d00** 2017-05-06 14:58 UTC
Labels: duplicate

**Comment by cweiske** [comment] 2017-05-06 15:52
And #73 was actually opened by me... had already forgotten about that.
